### ISSUE TITLE
CSV export/import function

### ISSUE THREAD

**Issue by Idrasil** [gilestrolab/pySolo#8]
Hello,
When using the PySolo - Database window, I get an error when trying to import a CSV file (File "pysolo_dv.pyo", line 999 in OnImportFromCSV Attribute Error: 'DAMlist'object has no attribute 'append'

I get this error even if I create a database, export it in CSV, restart the software and import the CSV.

Platform win 8.1.

Best,

Andrea

**Comment by Idrasil** [comment]
Sorry for the late reply!

I used the compiled version on pysolo.net (1.0)

I also installed Python 2.7 32 bits and:
- wxPython3.0 win32 python 2.7
- matplotlib 1.4.2 win32 py2.7
- numpy 1.9.1 win32 py2.7
- scipy 0.15.0 win32 py2.7

in that order and tried to run the pysolo.py from the release on github and failed to start the software:
Screenshot of shell: http://imgur.com/j5dzmsS 

I am new with Python so I don't know if I missed a step...

Best!

**Comment by Idrasil** [comment]
I installed the following packages: six, dateutil and pyparsing.
got a new error:

C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master>pysolo.py
Traceback (most recent call last):
  File "C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\pysolo.py", line 61, in <module>
    app=MyApp()
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\pysolo.py", line 42, in OnInit
    from pysolo_db import pySolo_DBFrame
  File "C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\pysolo_db.py", line 8, in <module>
    from default_panels import CustTableGrid, gridlib, SavePreferenceFile, FileDrop
  File "C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\panels\default_panels.py", line 33, in <module>
    import wxmpl
  File "C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\wxmpl.py", line 25, in <module>
    from matplotlib.axes import _process_plot_var_args
ImportError: cannot import name _process_plot_var_args

**Comment by ggilestro** [comment]
It seems in matplotlib 1.4.2 that class has moved. I've fix it in the developmental version; you should either you the github version or else you can fix it yourself by changing line 25 in the file C:\Data\EPFL\Datas\Fly project\Pysolo\pySolo-master\wxmpl.py

Replace
 from matplotlib.axes import _process_plot_var_args 
with
 from matplotlib.axes._base import _process_plot_var_args
